// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Clean up expired verifications
	CleanUpVerifications(ctx context.Context) error
	// Delete a user by ID
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	// Find a user by email
	FindUserByEmail(ctx context.Context, email string) (User, error)
	// Find a user by ID
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Find a verification by ID
	FindVerificationByID(ctx context.Context, id uuid.UUID) (Verification, error)
	// Store or update a user
	StoreOrUpdateUser(ctx context.Context, email string) (User, error)
	// Store or update a user's verification code.
	StoreOrUpdateVerification(ctx context.Context, arg StoreOrUpdateVerificationParams) (Verification, error)
	// Update a user's email by ID
	UpdateUserEmailByID(ctx context.Context, arg UpdateUserEmailByIDParams) error
}

var _ Querier = (*Queries)(nil)
